---
  files:
    include:
      - "src/sass/*"
  rules:
    bem-depth: 0
    border-zero:
      - 2
      -
        convention: "none"
    brace-style:
      - 2
      -
        style: "1tbs"
        allow-single-line: true
    class-name-format:
      - 2
      -
        allow-leading-underscore: false
        convention: "hyphenatedlowercase"
    clean-import-paths:
      - 2
      -
        leading-underscore: false
        filename-extension: true
    empty-args:
      - 2
      -
        include: false
    empty-line-between-blocks:
      - 2
      -
        include: true
        allow-single-line-rulesets: true
    extends-before-declarations: 2
    extends-before-mixins: 2
    final-newline:
      - 2
      -
        include: true
    force-attribute-nesting: 0
    force-element-nesting: 1
    force-pseudo-nesting: 0
    function-name-format:
      - 2
      -
        allow-leading-underscore: false
        convention: "hyphenatedlowercase"
    hex-length:
      - 2
      -
        style: "long"
    hex-notation:
      - 2
      -
        style: "lowercase"
    id-name-format:
      - 2
      -
        allow-leading-underscore: false
        convention: "hyphenatedlowercase"
    indentation:
      - 2
      -
        size: 1
    leading-zero:
      - 2
      -
        include: true
    mixin-name-format:
      - 2
      -
        allow-leading-underscore: false
        convention: "hyphenatedlowercase"
    mixins-before-declarations:
      - 2
      -
        exclude:
          - "breakpoint"
          - "mq"
    nesting-depth:
      - 2
      -
        max-depth: 3
    no-color-keywords: 2
    no-color-literals: 0
    no-css-comments: 2
    no-debug: 1
    no-duplicate-properties:
      - 2
      -
        exclude: []
    no-empty-rulesets: 2
    no-important: 1
    no-invalid-hex: 2
    no-mergeable-selectors:
      - 2
      -
        whitelist: []
    no-misspelled-properties:
      - 2
      -
        extra-properties: []
    no-qualifying-elements: 0
    no-trailing-whitespace: 2
    no-trailing-zero: 2
    no-transition-all: 2
    no-url-protocols: 0
    no-vendor-prefixes:
      - 2
      -
        additional-identifiers:
          - "o"
        excluded-identifiers: []
    no-extends: 0
    no-ids: 1
    no-warn: 1
    one-declaration-per-line: 2
    placeholder-in-extend: 0
    placeholder-name-format:
      - 2
      -
        allow-leading-underscore: false
        convention: "hyphenatedlowercase"
    property-sort-order:
      - 2
      -
        order: "alphabetical"
        ignore-custom-properties: false
    property-units:
      - 2
      -
        global:
          - "em"
          - "px"
          - "vh"
          - "vw"
        per-property:
          font-size:
            - "rem"
    quotes:
      - 2
      -
        style: "double"
    shorthand-values:
      - 2
      -
        allowed-shorthands:
          - 1
          - 2
    single-line-per-selector: 0
    space-after-bang: 0
    space-after-colon: 2
    space-after-comma: 2
    space-around-operator:
      - 2
      -
        include: true
    space-before-bang: 2
    space-before-brace:
      - 2
      -
        include: true
    space-before-colon:
      - 2
      -
        include: false
    space-between-parens:
      - 2
      -
        include: false
    trailing-semicolon:
      - 2
      -
        include: true
    url-quotes: 2
    variable-for-property:
      - 2
      -
        properties: []
    variable-name-format:
      - 2
      -
        allow-leading-underscore: false
        convention: "hyphenatedlowercase"
    zero-unit:
      - 2
      -
        include: false
